version: "3.7"

services:
  app:
    build: .
    command: "npm run dev"
    ports:
      - "3000:3000"
    volumes:
        - .:/usr/src/app

    networks:
      - app-network

  db:
    container_name: mysql8
    image: mysql:8.0.33
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: local
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - '3306:3306'
    networks:
      - app-network

networks:
    app-network:
        driver: bridge